#/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
. $SCRIPT_DIR/oasis_env.sh

CONFIG_VALUE=""

config_value "OASIS_CORE_VERSION ex: 21.3.3" "$OASIS_CORE_VERSION"
CONFIG_OASIS_CORE_VERSION="$CONFIG_VALUE"

config_value "OASIS_GENESIS_URL ex: https://github.com/oasisprotocol/testnet-artifacts/releases/download/2021-04-13/genesis.json" "$OASIS_GENESIS_URL"
CONFIG_OASIS_GENESIS_URL="$CONFIG_VALUE"

config_value "OASIS_SEED_NODE ex: 05EAC99BB37F6DAAD4B13386FF5E087ACBDDC450@34.86.165.6:26656" "$OASIS_SEED_NODE"
CONFIG_OASIS_SEED_NODE="$CONFIG_VALUE"

mkdir -p $CONFIG_NETWORK_DIR

cat >$CONFIG_NETWORK_DIR/network_config.sh << EOF
CUSTOM_OASIS_CORE_VERSION="$CONFIG_OASIS_CORE_VERSION"
CUSTOM_OASIS_GENESIS_URL="$CONFIG_OASIS_GENESIS_URL"
CUSTOM_OASIS_SEED_NODE="$CONFIG_OASIS_SEED_NODE"
EOF

cat $CONFIG_NETWORK_DIR/network_config.sh

