#/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
. $SCRIPT_DIR/oasis_env.sh

echo #NETWORK
echo CUSTOM_OASIS_CORE_VERSION $CUSTOM_OASIS_CORE_VERSION
echo CUSTOM_OASIS_GENESIS_URL $CUSTOM_OASIS_GENESIS_URL
echo CUSTOM_OASIS_SEED_NODE $CUSTOM_OASIS_SEED_NODE
echo #TYPE
echo CUSTOM_OASIS_CORE_VERSION $CUSTOM_OASIS_CORE_VERSION
echo CUSTOM_OASIS_GENESIS_URL $CUSTOM_OASIS_GENESIS_URL
echo CUSTOM_OASIS_SEED_NODE $CUSTOM_OASIS_SEED_NODE
echo CUSTOM_LATEST_TIME_ERROR="$CUSTOM_LATEST_TIME_ERROR"
echo CUSTOM_PARATIME_RUNTIME_IDENTIFIER $CUSTOM_PARATIME_RUNTIME_IDENTIFIER
echo CUSTOM_PARATIME_RUNTIME_VERSION $CUSTOM_PARATIME_RUNTIME_VERSION
echo CUSTOM_PARATIME_RUNTIME_SGSX $CUSTOM_PARATIME_RUNTIME_SGSX
echo CUSTOM_PARATIME_RUNTIME_SIG $CUSTOM_PARATIME_RUNTIME_SIG
echo CUSTOM_PARATIME_RUNTIME_IAS $CUSTOM_PARATIME_RUNTIME_IAS
echo #NODE
echo CUSTOM_OASIS_NODE_ENTITY $CUSTOM_OASIS_NODE_ENTITY
echo CUSTOM_OASIS_NODE_NETWORK $CUSTOM_OASIS_NODE_NETWORK
echo CUSTOM_OASIS_NODE_TYPE $CUSTOM_OASIS_NODE_TYPE
echo CUSTOM_OASIS_NODE_ROOT_DIR $CUSTOM_OASIS_NODE_ROOT_DIR
echo CUSTOM_OASIS_NODE_ADDR $CUSTOM_OASIS_NODE_ADDR
echo CUSTOM_OASIS_NODE_PORT $CUSTOM_OASIS_NODE_PORT
echo CUSTOM_OASIS_NODE_SSH_NAME $CUSTOM_OASIS_NODE_SSH_NAME
echo CUSTOM_OASIS_NODE_SSH $CUSTOM_OASIS_NODE_SSH
echo CUSTOM_OASIS_NODE_SSH_ADMIN_NAME $CUSTOM_OASIS_NODE_SSH_ADMIN_NAME
echo CUSTOM_OASIS_NODE_SSH_ADMIN $CUSTOM_OASIS_NODE_SSH_ADMIN
echo CUSTOM_OASIS_NODE_SSH_ID $CUSTOM_OASIS_NODE_SSH_ID
echo CUSTOM_OASIS_P2P_PORT $CUSTOM_OASIS_P2P_PORT

